### ISSUE TITLE
Unable to use apache vhosts routing for default skeleton app on a shared server

### ISSUE THREAD

**Issue by divix1988** [laminas/tutorials#10]
### Bug Report

I am unable to run successfully the Laminas MVC plain skeleton by injecting such lines into Apache's httpd-vhosts.conf file:

```
DocumentRoot "E:/RZECZY_ADAMA/_XAMPP/xampp-7.4/htdocs/laminas_folder/public"
ServerName localhost/laminas_folder
```

If the above is no longer supported then what would be an alternative?

I don't want to use:

```
<VirtualHost *:80>
    ServerName localhost/laminasapp
    DocumentRoot E:/RZECZY_ADAMA/_XAMPP/xampp-7.4/htdocs/laminas_folder/public
    <Directory E:/RZECZY_ADAMA/_XAMPP/xampp-7.4/htdocs/laminas_folder/public>
        DirectoryIndex index.php
        AllowOverride All
        Order allow,deny
        Allow from all
        <IfModule mod_authz_core.c>
        Require all granted
        </IfModule>
    </Directory>
</VirtualHost>
```

Which takes over whole server, regardless of the URL address.

#### Summary

Unable to use vhost for skeleton app using latest XAMPP 7.4

#### Current behavior

Getting 404 routing error and broken images.

#### How to reproduce

- install plain skeleton
- edit httpd-vhosts.conf file with the above
- run: http://localhost/laminas_folder

#### Expected behavior

We should get a default Laminas MVC dashboard when accessing http://localhost/laminas_folder and we should be able to access http://localhost/project2 which is another PHP project (not Laminas).

**Comment by alexivaylov** [comment]
@divix1988 the documenation is correct. Your string `ServerName localhost/laminasapp` is not a valid apache vhost ServerName. Please make sure you understand the difference between vhosts and subdirectories. The laminas documentation shows an example of how to get a vhost for your Laminas project. However, what you are trying to do is run the app inside a subdirectory. Those are 2 different approaches. The vhost approach is the recommended one (where you also edit your hosts file) as it is per the Laminas documentation. Running it inside a sub-directory is an advanced approach and you would need to know Apache very well to do it. There's a link at the bottom that gives you an idea but it is not recommended.


See:
https://httpd.apache.org/docs/2.4/vhosts/index.html
https://httpd.apache.org/docs/2.4/vhosts/name-based.html
https://stackoverflow.com/questions/14403071/zend-framework-2-in-a-subdirectory?noredirect=1&lq=1

@froschdesign I believe this issue can be closed as the documentation is correct.

**Comment by froschdesign** [comment]
@alexivaylov 
Thanks for the detailed answer and the clarification!

**Comment by divix1988** [comment]
So running a Laminas on a shared hosting (most of small projects use that) with no access to vhosts file is an "advanced usage"? Interesting..

**Comment by froschdesign** [comment]
@divix1988 
You do not need a virtual host to run an application but this is a usage question, please ask them on the [forum](https://discourse.laminas.dev/).

Thanks in advance!
