### ISSUE TITLE
AlbumController::setUp is not compatible with declaration in AbstractControllerTestCase

### ISSUE THREAD

**Issue by Jem72** [laminas/tutorials#15]
### Bug Report

|    Q        |   A
|------------ | ------
| PHP  | 7.4.3

#### Summary

Running the test case in the tutorial results in a Fatal Error. This is because the setUp function is declared as
`protected function setUp(): void`
but the tutorial has not been updated accordingly

#### How to reproduce
1. Implement the code block in "Your First Controller Block" (https://docs.laminas.dev/tutorials/unit-testing/#your-first-controller-test)
2. Execute the test using "vendor/bin/phpunit --testsuite Album"
3. Results in "Fatal error: Declaration of AlbumTest\Controller\AlbumControllerTest::setUp() must be compatible with Laminas\Test\PHPUnit\Controller\AbstractControllerTestCase::setUp(): void "

#### Expected behavior
At step 3, we should get "OK (1 test, 5 assertions)

**Comment by michalbundyra** [comment]
@Jem72 Thanks for reporting. Would you like provide PR with the fixes? Thanks

**Comment by Xerkus** [comment]
It is not a bug. PHPUnit 7 or below should be required for this tutorial.

**Comment by michalbundyra** [comment]
@Xerkus not true, PHPUnit version does not matter. Just PHP version matters here.
And there is no point to using examples for PHP 5.6 anymore as it is no longer supported.

**Comment by Xerkus** [comment]
@michalbundyra PHPUnit version matters very much as it is not specified at all in https://docs.laminas.dev/tutorials/unit-testing/#installing-laminas-test while the tutorial code targets PHPUnit below 8.

https://github.com/laminas/laminas-test/blob/1fc9a4bf73eb146589aa9006a4c0b7fe9ec10a24/composer.json#L39
```
        "phpunit/phpunit": "^4.0 || ^5.0 || ^6.0 || ^7.0 || ^8.0 || ^9.0"
```
