### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by FraGoTe** [laminas/tutorials#2]
Are you guys planning to add i18n support to the documentation page?

**Comment by froschdesign** [comment]
@FraGoTe 
I'm afraid I don't see your point.

In the tutorials you will find a section "[Internationalization](https://docs.laminas.dev/tutorials/i18n/)" and the documentation of laminas-i18n can be found under the components: https://docs.laminas.dev/laminas-i18n/

Or do you mean something else?

**Comment by michalbundyra** [comment]
@froschdesign _I think_ the question is if we are planning translate documentation to other languages.

**Comment by FraGoTe** [comment]
I see thank you!
