### ISSUE TITLE
Links broken on quickstart guide https://docs.laminas.dev/laminas-mvc/quick-start/

### ISSUE THREAD

**Issue by flipkickmedia** [laminas/tutorials#29]
Links are broken in the content on the quick start page for the LaminasSkeletonModule zip package and 
LaminasSkeletonModule tarball download links - git hub returns a 404

https://docs.laminas.dev/laminas-mvc/quick-start/

**Comment by froschdesign** [comment]
Duplicate of https://github.com/laminas/laminas-mvc/issues/41
