### ISSUE TITLE
Remove install instructions for Vagrant

### ISSUE THREAD

**Issue by PAStheLoD** [laminas/tutorials#33]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | mvc-skeleton 1.2.0 12ff936

#### Summary

In case this is not the correct repository for report this bug, please help me find the right one. Thanks!

Basically the problem is that NTFS and ext4 and vboxsf doesn't really get along. (Symlink handling is an instant no-no, but even simple things like deleting files will cause problems, if for some reason the host side thinks that VirtualBox shouldn't be doing that. Maybe the file is open because VS Code saw a .git folder somewhere and thinks now is the time to index its contents.)

#### Current behavior

Following this tutorial: https://docs.laminas.dev/tutorials/getting-started/skeleton-application/

After vagrant up successfully completes running `$ vagrant ssh -c 'composer install'` leads to this error:

```
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 22 installs, 0 updates, 0 removals
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.
  - Installing laminas/laminas-component-installer (2.4.0): Extracting archive
Plugin initialization failed (Plugin laminas/laminas-component-installer could not be initialized, class not found: Laminas\ComponentInstaller\ComponentInstaller), uninstalling plugin
  - Removing laminas/laminas-component-installer (2.4.0)
    Install of laminas/laminas-component-installer failed


  [RuntimeException]
  Could not delete /var/www/vendor/laminas/laminas-component-installer/src:
```

I'd recommend documenting that Windows users should install WAMP and not try to use Vagrant, to avoid this dead-end. (Or solve the vboxsf issues, but I think VirtualBox devs are trying to come up for good solutions for these for about a decade.)

**Comment by froschdesign** [comment]
@PAStheLoD 
Thanks for reporting this problem. 👍 
We will tighten up the explanations to ensure a smooth start.

---

I don't use Vagrant myself, but have you tried the plugin [vagrant-winnfsd](https://github.com/winnfsd/vagrant-winnfsd)?

**Comment by PAStheLoD** [comment]
Hello! Thanks for the quick reply!

I haven't tried NFS in this case (but when I tried it with a Python project a few months ago, and basically the same result - just a matter of time before something comes up). So in general I found that with great tools like scoop for Windows it's easy to get a sort of reliable dev env setup going. (And just use Vagrant for the DB and other backing services. Plus it's easy to script the host side setup via a bit of Ruby.)

**Comment by froschdesign** [comment]
Until now, the only plan was to restructure the page for skeleton application and the different kinds of installations. But we will have to re-evaluate the tools to offer the best possible entry and choice.
Therefore every informations from all practical uses are welcome!
