### ISSUE TITLE
Broken Link in MVC Tutorials

### ISSUE THREAD

**Issue by diegofariasdev** [laminas/tutorials#35]
Huy guys! 
Looks like this paragraph in https://docs.laminas.dev/tutorials/getting-started/database-and-models/ has a broken link:

`This method returns an array of factories that are all merged together by the ModuleManager before passing them to the ServiceManager. The factory for Album\Model\AlbumTable uses the ServiceManager to create an Album\Model\AlbumTableGateway service representing a TableGateway to pass to its constructor. We also tell the ServiceManager that the AlbumTableGateway service is created by fetching a Laminas\Db\Adapter\AdapterInterface implementation (also from the ServiceManager) and using it to create a TableGateway object. The TableGateway is told to use an Album object whenever it creates a new result row. The TableGateway classes use the prototype pattern for creation of result sets and entities. This means that instead of instantiating when required, the system clones a previously instantiated object. See PHP Constructor Best Practices and the Prototype Pattern for more details. `

**Comment by froschdesign** [comment]
The article is no longer available and we need to find an alternative or remove the link.

**Comment by Sirpyerre** [comment]
Can you change the link with this https://refactoring.guru/design-patterns/prototype/php/example?

**Comment by froschdesign** [comment]
@Sirpyerre 
The original article was copied and is still available. See #39
