### ISSUE TITLE
 Highlight additional `use` in module.config.php

### ISSUE THREAD

**Issue by RussellAult** [laminas/tutorials#45]
I was running through the tutorial and got an error about the "Album\\Segment" plugin not being found. Turns out I had missed a `use` in "Routing and Controllers" because it wasn't highlighted with a comment like the rest of the adds were.

I created a patch at RussellAult/tutorials@9bf54fbcb36a9c4c6c20c1300d65103fabfd2c27 and then created a PR, but I closed it when I realized that a DCO sign off was involved (I use GitHub through the web interface).

**Comment by froschdesign** [comment]
We can highlight lines directly, I will add this.
