### ISSUE TITLE
error http 500 when adding album to modules.config.php

### ISSUE THREAD

**Issue by samg1** [laminas/tutorials#48]
Hi, I am just trying to follow the tutorial to get to know the framework, but I cannot go past the  step where you add the Album module to the list of modules in modules.config.php
It immediately goes into a 500 http error.
I have followed the tutorial several times and tried multple solutions but nothing seems to work. Does anyone have an idea on why this could be happening?
![sample2](https://user-images.githubusercontent.com/49925704/132267749-dad521d2-9fa4-4953-b8c7-292dc29d6ca4.PNG)
![sample1](https://user-images.githubusercontent.com/49925704/132267755-904495e3-2c81-41c4-9ad5-d72485d9acf7.PNG)

I am using windows 10, php 7.2 and the PHP built in server

**Comment by froschdesign** [comment]
You have already asked the question in the forum: https://discourse.laminas.dev/t/http-error-500-when-adding-module-to-modules-config/2496/3
