### ISSUE TITLE
Incomplete tutorial

### ISSUE THREAD

**Issue by Tyrsson** [laminas/tutorials#60]
### Bug Report

Not to actually say its incomplete... It just introduces topics that are then not covered or used in the rest of the tutorial, which makes it appear incomplete.

The tutorial here:
https://docs.laminas.dev/tutorials/in-depth-guide/preparing-databases/#adding-command-abstraction

Introduces
interface PostCommandInterface

However, the tutorial never mentions the interface again in the page that introduces it or the following page which concludes that portion of the tutorials. The Next section is understanding the router.

**Comment by froschdesign** [comment]
> It just introduces topics that are then not covered or used in the rest of the tutorial, which makes it appear incomplete.

Please see: https://docs.laminas.dev/tutorials/in-depth-guide/laminas-form-laminas-form-fieldset/#creating-the-writecontroller
