### ISSUE TITLE
Duplicated migration guide

### ISSUE THREAD

**Issue by michalbundyra** [laminas/tutorials#8]
### Bug Report

It looks like we have duplicated migration guide:
- https://docs.laminas.dev/tutorials/migration-from-zendframework/
- https://docs.laminas.dev/migration/

I think we would need to keep it just in one place and redirect the other one, as now any fixes or changes we have to do in these two places.

**Comment by froschdesign** [comment]
Migration is a separated topic and should not be listed under the tutorials. And duplication of content results in problems.

**Comment by froschdesign** [comment]
Fixed with #11
